// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA25chjh-y7dcb7KwwxkeYiby2VHgMRfks',
    appId: '1:161856152695:web:23bb0a88969cc1afa91272',
    messagingSenderId: '161856152695',
    projectId: 'sm-sports-med',
    authDomain: 'sm-sports-med.firebaseapp.com',
    storageBucket: 'sm-sports-med.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZc43EU2It6E6bz2T0YYJyR8liT3cQJF4',
    appId: '1:161856152695:android:f1ed80bc3bbf4cb9a91272',
    messagingSenderId: '161856152695',
    projectId: 'sm-sports-med',
    storageBucket: 'sm-sports-med.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZg0O6THcL0rihPQmIVKLHgdvie15h7_U',
    appId: '1:161856152695:ios:3e07c5f9c560017fa91272',
    messagingSenderId: '161856152695',
    projectId: 'sm-sports-med',
    storageBucket: 'sm-sports-med.appspot.com',
    iosBundleId: 'com.example.sportApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZg0O6THcL0rihPQmIVKLHgdvie15h7_U',
    appId: '1:161856152695:ios:3e07c5f9c560017fa91272',
    messagingSenderId: '161856152695',
    projectId: 'sm-sports-med',
    storageBucket: 'sm-sports-med.appspot.com',
    iosBundleId: 'com.example.sportApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA25chjh-y7dcb7KwwxkeYiby2VHgMRfks',
    appId: '1:161856152695:web:e8b8ea7cf0082498a91272',
    messagingSenderId: '161856152695',
    projectId: 'sm-sports-med',
    authDomain: 'sm-sports-med.firebaseapp.com',
    storageBucket: 'sm-sports-med.appspot.com',
  );

}